CREATE TABLE animals (
    id INT  AUTO_INCREMENT PRIMARY KEY,
    vardas VARCHAR(50) NOT NULL,
    rusis VARCHAR(50) NOT NULL,
    svoris FLOAT NOT NULL,
    aplinka VARCHAR(50) NOT NULL,
    lt BOOLEAN NOT NULL
);

INSERT INTO animals (vardas, rusis, svoris, aplinka, lt) VALUES
('ežys', 'žinduolis', 1.0, 'sausuma', 1),
('gandras', 'paukštis', 3.5, 'oras', 1),
('ryklys', 'žuvis', 500.0, 'vanduo', 0),
('varlė', 'varliagyvis', 0.2, 'vanduo', 1),
('vėžlys', 'roplys', 1.1, 'sausuma', 1),
('karvė', 'žinduolis', 600.0, 'sausuma', 1),
('pelėda', 'paukštis', 2.0, 'oras', 1),
('šamas', 'žuvis', 80.0, 'vanduo', 1),
('lapė', 'žinduolis', 8.0, 'sausuma', 1),
('žaltys', 'roplys', 0.8, 'sausuma', 1),
('meška', 'žinduolis', 300.0, 'sausuma', 1),
('antis', 'paukštis', 2.2, 'vanduo', 1),
('delfinas', 'žinduolis', 150.0, 'vanduo', 0),
('zylė', 'paukštis', 0.02, 'oras', 1),
('katė', 'žinduolis', 4.0, 'sausuma', 1),
('šuo', 'žinduolis', 25.0, 'sausuma', 1),
('krokodilas', 'roplys', 400.0, 'vanduo', 0),
('žirafa', 'žinduolis', 800.0, 'sausuma', 0),
('liūtas', 'žinduolis', 190.0, 'sausuma', 0),
('dramblys', 'žinduolis', 5000.0, 'sausuma', 0),
('pingvinas', 'paukštis', 20.0, 'vanduo', 0),
('upinis vėžys', 'bestuburis', 0.15, 'vanduo', 1),
('bitė', 'bestuburis', 0.001, 'oras', 1),
('žuvis', 'žuvis', 0.5, 'vanduo', 1),
('barsukas', 'žinduolis', 12.0, 'sausuma', 1),
('elnias', 'žinduolis', 180.0, 'sausuma', 1),
('ožka', 'žinduolis', 65.0, 'sausuma', 1),
('gulbė', 'paukštis', 14.0, 'vanduo', 1),
('kiškis', 'žinduolis', 2.5, 'sausuma', 1),
('lokys', 'žinduolis', 350.0, 'sausuma', 1),
('kirmėlė', 'bestuburis', 0.01, 'po žeme', 1),
('šakninė žiurkė', 'žinduolis', 0.3, 'po žeme', 1),
('pelė', 'žinduolis', 0.1, 'po žeme', 1);
